In [18]:
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
file = "/home/olivier/repositories/nf-core-stableexpression/test/selected_accession_to_nb_samples.csv"
df = pd.read_csv(file)

In [24]:
df

         accession  nb_samples
0      E-MTAB-3578         122
1     E-GEOD-52564          17
2     E-GEOD-49906          11
3     E-MTAB-11442          12
4      E-MTAB-2582          12
...            ...         ...
1278    E-TABM-755           8
1279    E-TABM-778          16
1280    E-TABM-865          23
1281     E-TABM-89          30
1282    E-TABM-903          56

[1283 rows x 2 columns]

In [25]:
df.describe()

        nb_samples
count  1283.000000
mean     20.771629
std      79.120320
min       4.000000
25%       7.000000
50%      12.000000
75%      18.000000
max    2660.000000

In [26]:
df["nb_samples"].sum()

np.int64(26650)